# Generated by Django 3.2.15 on 2023-08-30 06:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0002_basket'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='product',
            options={'verbose_name': 'продукт', 'verbose_name_plural': 'продукты'},
        ),
        migrations.AlterModelOptions(
            name='productscategory',
            options={'verbose_name': 'категории', 'verbose_name_plural': 'категории'},
        ),
    ]
